name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: extractions/setup-crate@v1
      with:
        owner: sigoden
        name: argc

    - name: Check versions
      run: argc version

    - name: Setup Python
      uses: actions/setup-python@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1

    - name: Run Test
      run: argc test