name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: sigoden/install-binary@v1
      with:
        repo: sigoden/argc

    - name: Check versions
      run: argc version

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Link web-search and code-interpreter
      run: |
        argc link-web-search web_search_perplexity.sh 
        argc link-code-interpreter execute_py_code.py 

    - name: Run Test
      run: argc test
      env:
        PYTHONIOENCODING: utf-8 